'use client';

import { useCallback, useEffect, useState } from 'react';
import { Download, FileBarChart2, RefreshCw } from 'lucide-react';
import { repaymentReportsService, type RepaymentReport } from '@/services/repayment-reports.service';
import { useToast } from '@/components/ui/Toast';

const money = (value = 0) => new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES', maximumFractionDigits: 0 }).format(value);
export function RepaymentReportView() {
  const toast = useToast(); const [startDate, setStartDate] = useState('2026-08-01'); const [endDate, setEndDate] = useState('2026-09-12'); const [report, setReport] = useState<RepaymentReport | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setReport(await repaymentReportsService.generate({ startDate, endDate })); } catch { toast.error('Could not generate the repayment report.'); } finally { setLoading(false); } }, [startDate, endDate, toast]);
  useEffect(() => { load(); }, [load]);
  const exportCsv = () => { if (!report) return; const rows = [['Reference', 'Facility', 'Amount', 'Status', 'Source', 'Initiated'], ...report.records.map((item) => [item.reference ?? item.id, item.facilityId, String(item.totalAmount), item.status, item.source ?? 'MANUAL', item.initiatedAt ?? ''])]; const blob = new Blob([rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `repayment-report-${startDate}-${endDate}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  return <main className="mx-auto min-h-screen max-w-[1600px] space-y-6 bg-slate-50 p-6"><header className="flex flex-col gap-4 border-b border-slate-200 pb-5 md:flex-row md:items-center md:justify-between"><div><h1 className="text-2xl font-bold text-slate-900">Repayment Report</h1><p className="mt-1 text-sm text-slate-500">Summary of repayment activity for the selected period.</p></div><button onClick={exportCsv} disabled={!report} className="inline-flex items-center gap-2 rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Download size={16} /> Export CSV</button></header><section className="flex flex-wrap items-end gap-3 rounded-xl border border-slate-200 bg-white p-4"><label className="text-sm font-medium text-slate-700">Start date<input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} className="mt-1 block rounded-lg border border-slate-200 p-2" /></label><label className="text-sm font-medium text-slate-700">End date<input type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} className="mt-1 block rounded-lg border border-slate-200 p-2" /></label><button onClick={load} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700"><RefreshCw size={16} /> Generate</button></section>{loading ? <div className="rounded-xl bg-white p-10 text-center text-slate-500">Generating report…</div> : report && <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total repaid" value={money(report.totalRepaid)} /><Stat label="Outstanding after repayments" value={money(report.totalOutstanding)} /><Stat label="Completed" value={String(report.completedTransactions)} /><Stat label="Pending / rejected" value={`${report.pendingTransactions} / ${report.rejectedTransactions}`} /></section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><FileBarChart2 className="text-blue-700" size={20} /><h2 className="font-bold text-slate-900">Transactions ({report.totalTransactions})</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Reference</th><th className="p-3">Facility</th><th className="p-3">Amount</th><th className="p-3">Source</th><th className="p-3">Status</th></tr></thead><tbody>{report.records.map((item) => <tr key={item.id} className="border-b border-slate-100"><td className="p-3 font-mono text-xs">{item.reference ?? item.id}</td><td className="p-3">{item.facilityId}</td><td className="p-3 font-semibold">{money(item.totalAmount)}</td><td className="p-3">{item.source ?? 'MANUAL'}</td><td className="p-3">{item.status.replaceAll('_', ' ')}</td></tr>)}</tbody></table></div></section></>}</main>;
}
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-xl font-bold text-slate-900">{value}</p></div>; }
